// <auto-generated />
using System;
using IntershipsDEIS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntershipsDEIS.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("IntershipsDEIS.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("IntershipId");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("Name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProjectId");

                    b.Property<string>("ProjectId1");

                    b.Property<string>("Role");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("IntershipId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ProjectId1");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.EvaluateCompany", b =>
                {
                    b.Property<string>("EvaluateCompanyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CompanyId");

                    b.Property<string>("Justification")
                        .IsRequired();

                    b.Property<int>("Pontuation");

                    b.Property<string>("StudentId");

                    b.HasKey("EvaluateCompanyId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.ToTable("EvaluateCompany");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.EvaluateStudent", b =>
                {
                    b.Property<string>("EvaluateStudentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EntityId");

                    b.Property<string>("Justification")
                        .IsRequired();

                    b.Property<int>("Pontuation");

                    b.Property<string>("StudentId");

                    b.HasKey("EvaluateStudentId");

                    b.HasIndex("EntityId");

                    b.HasIndex("StudentId");

                    b.ToTable("EvaluateStudent");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.Intership", b =>
                {
                    b.Property<string>("IntershipId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessConditions")
                        .IsRequired();

                    b.Property<string>("AdvisorId");

                    b.Property<int>("Branch");

                    b.Property<string>("CompanyId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Justification");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Objectives")
                        .IsRequired();

                    b.Property<int>("State");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("IntershipId");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Intership");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.IntershipCandidature", b =>
                {
                    b.Property<string>("IntershipCandidatureId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Branch");

                    b.Property<string>("CandidateId");

                    b.Property<DateTime>("DefenseDate");

                    b.Property<string>("Grades")
                        .IsRequired();

                    b.Property<string>("IntershipId");

                    b.Property<int>("Result");

                    b.Property<string>("UnfinishedGrades")
                        .IsRequired();

                    b.HasKey("IntershipCandidatureId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("IntershipId");

                    b.ToTable("IntershipCandidature");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.Message", b =>
                {
                    b.Property<string>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("RecipientId")
                        .IsRequired();

                    b.Property<string>("SenderId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<bool>("read");

                    b.HasKey("MessageId");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.Project", b =>
                {
                    b.Property<string>("ProjectId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessConditions")
                        .IsRequired();

                    b.Property<int>("Branch");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Justification");

                    b.Property<string>("Objectives")
                        .IsRequired();

                    b.Property<int>("State");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("ProjectId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.ProjectCandidature", b =>
                {
                    b.Property<string>("ProjectCandidatureId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Branch");

                    b.Property<string>("CandidateId");

                    b.Property<DateTime>("DefenseDate");

                    b.Property<string>("Grades")
                        .IsRequired();

                    b.Property<string>("ProjectId");

                    b.Property<int>("Result");

                    b.Property<string>("UnfinishedGrades")
                        .IsRequired();

                    b.HasKey("ProjectCandidatureId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectCandidature");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.ApplicationUser", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.Intership")
                        .WithMany("Placed")
                        .HasForeignKey("IntershipId");

                    b.HasOne("IntershipsDEIS.Models.Project")
                        .WithMany("Placed")
                        .HasForeignKey("ProjectId");

                    b.HasOne("IntershipsDEIS.Models.Project")
                        .WithMany("Professors")
                        .HasForeignKey("ProjectId1");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.EvaluateCompany", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.EvaluateStudent", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId");

                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.Intership", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId");

                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.IntershipCandidature", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");

                    b.HasOne("IntershipsDEIS.Models.Intership", "Intership")
                        .WithMany("Candidatures")
                        .HasForeignKey("IntershipId");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.Message", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");
                });

            modelBuilder.Entity("IntershipsDEIS.Models.ProjectCandidature", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.ApplicationUser", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId");

                    b.HasOne("IntershipsDEIS.Models.Project", "Project")
                        .WithMany("Candidatures")
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IntershipsDEIS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IntershipsDEIS.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
